In [2]:
import pandas as pd
import numpy as np
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

from surprise import KNNWithMeans
from surprise import Dataset
from surprise import accuracy
from surprise.model_selection import train_test_split
from surprise import Reader

In [61]:
df_linkedIn_intitial = pd.read_csv('LinkedIn_Dataset_post_csv_final.csv')
df_linkedIn_intitial.head(10)

,FirstName,LastName,Location,NumConnections,Industry,Skill_a,Skill_b,Skill_c,Skill_d,Skill_e,...,Degree_b,FieldOfStudy_b,Degree_c,FieldOfStudy_c,positions_a_title,positions_a_company_name,positions_b_title,positions_b_company_name,positions_c_title,positions_c_company_name
0,hydros,achipravalappil,United Arab Emirates,36,Oil & Energy,Rotating Equipments in Oil & Gas Industry,Stationary Equipments in Oil & Gas Industry,Pneumatic System,Hydraulic System,CMMS - MAXIMO,...,NaN,NaN,NaN,NaN,Mechanical Maintenance Engineer,S.O.S Consultants,NaN,NaN,NaN,NaN
1,Hasnaa,ACHIQ,Maroc,131,Construction,Reporting & Analysis,SAP,Financial Control,Budgeting,overview on risks and opportunities,...,Cycle normal d'école de commerce,Finances et comptabilité,NaN,NaN,Contrôleur de gestion opérationnel Département,Cegelec,Contrôleur de gestion opérationnel Projet,Cegelec,Stagiaire en Finances et comptabilité,SEFIN Holding
2,Ali,Achir,Morocco,420,Public Relations and Communications,Event Planning,Teamwork,Customer Relations,Negotiation,Conservation,...,NaN,NaN,NaN,NaN,Student,Hassan II University,Customer Service Officer,Metlife-Alico,Customer Service Officer,Mashreq Bank
3,Nadjib,Achir,"Paris Area, France",99,Education Management,Wireless Sensor Networks,Wireless,QoS,NaN,NaN,...,NaN,NaN,NaN,NaN,Researcher,Université Paris 13 Nord,PHD Student,University of Paris 6,NaN,NaN
4,Meguru,Achira,Japan,121,Pharmaceuticals,Pharmacokinetics,DMPK,Clinical Development,Pharmacodynamics,Drug Metabolism,...,NaN,Pharmacokinetics,NaN,NaN,"Group Manager, Head of PK/PD Science Group",Janssen Pharmaceutical K.K.,NaN,NaN,NaN,NaN
5,Julio Alejandro,Achique Lopenza,Venezuela,125,Programas informáticos,Proactivo,Responsable,NaN,NaN,NaN,...,Ingeniero de Sistemas,Sistemas,NaN,NaN,Lider de Proyectos,STC Solutions Developers,Gerente de Sistemas,"Distribuidora Vivo, C.A.",Lider de Sistemas,"Vengas, C.A."
6,Mary Ann,Agpay,Qatar,500+,Apparel & Fashion,Fashion,Styling,Personal Shopping,Airbrush,NaN,...,NaN,Airline Secretarial,NaN,NaN,Fashion Stylist,La Vedette Fashion and Image Consulting,NaN,NaN,NaN,NaN
7,Daisy Anne,Agpoon,Philippines,60,Telecommunications,Event Hosting,Singing,Creative Writing,NaN,NaN,...,NaN,NaN,NaN,NaN,Talent Management Officer,"Smart Communications, Inc.",Senior Talent Acquisition Officer,UnionBank of the Philippines,Account Manager,"Gallardo & Associates, Inc."
8,Dean Michael,Agpoon,Singapore,18,Information Technology and Services,PeopleSoft,PeopleTools,PeopleCode,SQR,XML Publisher,...,NaN,NaN,NaN,NaN,IT Consultant (Oracle PeopleSoft),Citibank,Software Developer via Accenture,Large Utility Company,Software Developer via Accenture,Large Energy Provider
9,George,Agpoon,"Madison, Wisconsin Area",193,Online Media,Photoshop,Illustrator,Final Cut Studio,Adobe Premiere,After Effects,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
df_1 = df_linkedIn_intitial

In [63]:
df_1.head()

,FirstName,LastName,Location,NumConnections,Industry,Skill_a,Skill_b,Skill_c,Skill_d,Skill_e,...,Degree_b,FieldOfStudy_b,Degree_c,FieldOfStudy_c,positions_a_title,positions_a_company_name,positions_b_title,positions_b_company_name,positions_c_title,positions_c_company_name
0,hydros,achipravalappil,United Arab Emirates,36,Oil & Energy,Rotating Equipments in Oil & Gas Industry,Stationary Equipments in Oil & Gas Industry,Pneumatic System,Hydraulic System,CMMS - MAXIMO,...,NaN,NaN,NaN,NaN,Mechanical Maintenance Engineer,S.O.S Consultants,NaN,NaN,NaN,NaN
1,Hasnaa,ACHIQ,Maroc,131,Construction,Reporting & Analysis,SAP,Financial Control,Budgeting,overview on risks and opportunities,...,Cycle normal d'école de commerce,Finances et comptabilité,NaN,NaN,Contrôleur de gestion opérationnel Département,Cegelec,Contrôleur de gestion opérationnel Projet,Cegelec,Stagiaire en Finances et comptabilité,SEFIN Holding
2,Ali,Achir,Morocco,420,Public Relations and Communications,Event Planning,Teamwork,Customer Relations,Negotiation,Conservation,...,NaN,NaN,NaN,NaN,Student,Hassan II University,Customer Service Officer,Metlife-Alico,Customer Service Officer,Mashreq Bank
3,Nadjib,Achir,"Paris Area, France",99,Education Management,Wireless Sensor Networks,Wireless,QoS,NaN,NaN,...,NaN,NaN,NaN,NaN,Researcher,Université Paris 13 Nord,PHD Student,University of Paris 6,NaN,NaN
4,Meguru,Achira,Japan,121,Pharmaceuticals,Pharmacokinetics,DMPK,Clinical Development,Pharmacodynamics,Drug Metabolism,...,NaN,Pharmacokinetics,NaN,NaN,"Group Manager, Head of PK/PD Science Group",Janssen Pharmaceutical K.K.,NaN,NaN,NaN,NaN

In [82]:
df_1['Skills_new'] = df_1.Skill_a.astype(str).str.cat(df_1.Skill_b.astype(str), sep=' ').str.cat(df_1.Skill_c.astype(str), sep=' ').str.cat(df_1.Skill_d.astype(str), sep=' ').str.cat(df_1.Skill_e.astype(str), sep=' ')

In [83]:
df_1['Degrees_new'] = df_1.Degree_a.astype(str).str.cat(df_1.Degree_b.astype(str), sep=' ').str.cat(df_1.Degree_c.astype(str), sep=' ')

In [79]:
df_1['FieldOfStudy'] = df_1.FieldOfStudy_a.astype(str).str.cat(df_1.FieldOfStudy_b.astype(str), sep=' ').str.cat(df_1.FieldOfStudy_c.astype(str), sep=' ')

In [86]:
df_1['positions__title'] = df_1.positions_a_title.astype(str).str.cat(df_1.positions_b_title.astype(str), sep=',').str.cat(df_1.positions_c_title.astype(str), sep=',')

In [89]:
df_1['Company_Names'] = df_1.positions_a_company_name.astype(str).str.cat(df_1.positions_b_company_name.astype(str), sep=',').str.cat(df_1.positions_c_company_name.astype(str), sep=',')

In [92]:
df_1['Name'] = df_1.FirstName.astype(str).str.cat(df_1.LastName.astype(str), sep=' ')

In [93]:
df_1.head()

,FirstName,LastName,Location,NumConnections,Industry,Skill_a,Skill_b,Skill_c,Skill_d,Skill_e,...,positions_b_title,positions_b_company_name,positions_c_title,positions_c_company_name,Skills_new,Degrees_new,FieldOfStudy,positions__title,Company_Names,Name
0,hydros,achipravalappil,United Arab Emirates,36,Oil & Energy,Rotating Equipments in Oil & Gas Industry,Stationary Equipments in Oil & Gas Industry,Pneumatic System,Hydraulic System,CMMS - MAXIMO,...,NaN,NaN,NaN,NaN,Rotating Equipments in Oil & Gas Industry Stat...,Bachelor of Engineering (B.E.) nan nan,Mechanical Engineering nan nan,"Mechanical Maintenance Engineer,nan,nan","S.O.S Consultants,nan,nan",hydros achipravalappil
1,Hasnaa,ACHIQ,Maroc,131,Construction,Reporting & Analysis,SAP,Financial Control,Budgeting,overview on risks and opportunities,...,Contrôleur de gestion opérationnel Projet,Cegelec,Stagiaire en Finances et comptabilité,SEFIN Holding,Reporting & Analysis SAP Financial Control Bud...,Mastère spécialisé Cycle normal d'école de com...,"Audit, contrôle de gestion et systèmes d'infor...",Contrôleur de gestion opérationnel Département...,"Cegelec,Cegelec,SEFIN Holding",Hasnaa ACHIQ
2,Ali,Achir,Morocco,420,Public Relations and Communications,Event Planning,Teamwork,Customer Relations,Negotiation,Conservation,...,Customer Service Officer,Metlife-Alico,Customer Service Officer,Mashreq Bank,Event Planning Teamwork Customer Relations Neg...,M.S Management de la Communication des Organis...,Communication nan nan,"Student,Customer Service Officer,Customer Serv...","Hassan II University,Metlife-Alico,Mashreq Bank",Ali Achir
3,Nadjib,Achir,"Paris Area, France",99,Education Management,Wireless Sensor Networks,Wireless,QoS,NaN,NaN,...,PHD Student,University of Paris 6,NaN,NaN,Wireless Sensor Networks Wireless QoS nan nan,nan nan nan,nan nan nan,"Researcher,PHD Student,nan","Université Paris 13 Nord,University of Paris 6...",Nadjib Achir
4,Meguru,Achira,Japan,121,Pharmaceuticals,Pharmacokinetics,DMPK,Clinical Development,Pharmacodynamics,Drug Metabolism,...,NaN,NaN,NaN,NaN,Pharmacokinetics DMPK Clinical Development Pha...,"MS, Ph.D. nan nan",Pharmacokinetics Pharmacokinetics nan,"Group Manager, Head of PK/PD Science Group,nan...","Janssen Pharmaceutical K.K.,nan,nan",Meguru Achira

In [111]:
df__analyse_2 = df_1[['Name','Industry','positions__title','Company_Names','Skills_new','Degrees_new','FieldOfStudy']]

In [181]:
df__analyse_2.head()

,Name,Industry,positions__title,Company_Names,Skills_new,Degrees_new,FieldOfStudy,positions_title
0,hydros achipravalappil,Oil & Energy,[Mechanical Maintenance Engineer ],S.O.S Consultants,Rotating Equipments in Oil & Gas Industry Stat...,Bachelor of Engineering (B.E.),Mechanical Engineering,[Mechanical Maintenance Engineer ]
1,Hasnaa ACHIQ,Construction,[Contrôleur de gestion opérationnel Départemen...,"Cegelec,Cegelec,SEFIN Holding",Reporting & Analysis SAP Financial Control Bud...,Mastère spécialisé Cycle normal d'école de com...,"Audit, contrôle de gestion et systèmes d'infor...",[Contrôleur de gestion opérationnel Départemen...
2,Ali Achir,Public Relations and Communications,"[Student, Customer Service Officer, Customer S...","Hassan II University,Metlife-Alico,Mashreq Bank",Event Planning Teamwork Customer Relations Neg...,M.S Management de la Communication des Organis...,Communication,"[Student, Customer Service Officer, Customer S..."
3,Nadjib Achir,Education Management,"[Researcher, PHD Student ]","Université Paris 13 Nord,University of Paris 6",Wireless Sensor Networks Wireless QoS,nan,,"[Researcher, PHD Student ]"
4,Meguru Achira,Pharmaceuticals,"[Group Manager, Head of PK/PD Science Group ]",Janssen Pharmaceutical K.K.,Pharmacokinetics DMPK Clinical Development Pha...,"MS, Ph.D.",Pharmacokinetics Pharmacokinetics,"[Group Manager, Head of PK/PD Science Group ]"

#Removing nan from position name strings

In [120]:
#df__analyse_2['positions__title'] = df__analyse_2['positions__title'].str.replace('nan,',' ')

#df__analyse_2['positions__title'] = df__analyse_2['positions__title'].str.replace(', nan',' ')
#df__analyse_2['positions__title'] = df__analyse_2['positions__title'].str.replace(',nan',' ')
#df__analyse_2.head(20)

In [ ]:
#Removing nan from company name strings

In [123]:
#df__analyse_2['Company_Names'] = df__analyse_2['Company_Names'].str.replace('nan,',' ')
#df__analyse_2['Company_Names'] = df__analyse_2['Company_Names'].str.replace(',nan',' ')
#df__analyse_2['Company_Names'] = df__analyse_2['Company_Names'].str.replace(', nan',' ')
#df__analyse_2.head(20)

In [ ]:
#Removing nan from Skills_new strings

In [129]:
#df__analyse_2['Skills_new'] = df__analyse_2['Skills_new'].str.replace(' nan ',' ')
#df__analyse_2['Skills_new'] = df__analyse_2['Skills_new'].str.replace(' nan',' ')
#df__analyse_2['Company_Names'] = df__analyse_2['Company_Names'].str.replace(', nan',' ')
#df__analyse_2.head(20)

In [134]:
#df__analyse_2['Degrees_new'] = df__analyse_2['Degrees_new'].str.replace(' nan ',' ')
#df__analyse_2['Degrees_new'] = df__analyse_2['Degrees_new'].str.replace(' nan',' ')
#df__analyse_2['Company_Names'] = df__analyse_2['Company_Names'].str.replace(', nan',' ')
#df__analyse_2.head(5)

,Name,Industry,positions__title,Company_Names,Skills_new,Degrees_new,FieldOfStudy
0,hydros achipravalappil,Oil & Energy,Mechanical Maintenance Engineer,S.O.S Consultants,Rotating Equipments in Oil & Gas Industry Stat...,Bachelor of Engineering (B.E.),Mechanical Engineering nan nan
1,Hasnaa ACHIQ,Construction,Contrôleur de gestion opérationnel Département...,"Cegelec,Cegelec,SEFIN Holding",Reporting & Analysis SAP Financial Control Bud...,Mastère spécialisé Cycle normal d'école de com...,"Audit, contrôle de gestion et systèmes d'infor..."
2,Ali Achir,Public Relations and Communications,"Student,Customer Service Officer,Customer Serv...","Hassan II University,Metlife-Alico,Mashreq Bank",Event Planning Teamwork Customer Relations Neg...,M.S Management de la Communication des Organis...,Communication nan nan
3,Nadjib Achir,Education Management,"Researcher,PHD Student","Université Paris 13 Nord,University of Paris 6",Wireless Sensor Networks Wireless QoS,nan,nan nan nan
4,Meguru Achira,Pharmaceuticals,"Group Manager, Head of PK/PD Science Group",Janssen Pharmaceutical K.K.,Pharmacokinetics DMPK Clinical Development Pha...,"MS, Ph.D.",Pharmacokinetics Pharmacokinetics nan

In [138]:
#df__analyse_2['FieldOfStudy'] = df__analyse_2['FieldOfStudy'].str.replace(' nan ',' ')
#df__analyse_2['FieldOfStudy'] = df__analyse_2['FieldOfStudy'].str.replace('nan ',' ')
#df__analyse_2['Company_Names'] = df__analyse_2['Company_Names'].str.replace(', nan',' ')
#df__analyse_2.head(5)

In [140]:
#df__analyse_2.head(20)

In [144]:
separate_positions = df__analyse_2['positions__title']

'''for line in new_df_investor: 
        count+=1
        test1= str(line)
        sagar= test1.split("[")
        new_sagar = sagar[1:]
        temp = []
        for i in new_sagar:
            new_i = i.rstrip('||')
            newSAG = new_i.split('|')
            investor_name = newSAG[0]
            unique_inv[investor_name] = 1
            temp.append(newSAG[0]) 
            pranav_inv.append(newSAG[0])
            #print(pranav_inv) '''
#df_separate_position = pd.DataFrame(separate_positions)
#df_separate_position.head()

'for line in new_df_investor: \n        count+=1\n        test1= str(line)\n        sagar= test1.split("[")\n        new_sagar = sagar[1:]\n        temp = []\n        for i in new_sagar:\n            new_i = i.rstrip(\'||\')\n            newSAG = new_i.split(\'|\')\n            investor_name = newSAG[0]\n            unique_inv[investor_name] = 1\n            temp.append(newSAG[0]) \n            pranav_inv.append(newSAG[0])\n            #print(pranav_inv) '

In [152]:
#positions_split on , 
split_posits = []
posit_array = []
for pos in df__analyse_2['positions__title']:
    each_row = pos.split(",")
    split_posits.append(each_row)
#print(split_posits)

In [170]:
datafr_split_posits = pd.Series(split_posits)
datafr_split_posits.head()
New_datafr_split_posits = pd.DataFrame(datafr_split_posits)

df__analyse_2['positions_title'] = New_datafr_split_posits
df__analyse_2.head()

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

,Name,Industry,positions__title,Company_Names,Skills_new,Degrees_new,FieldOfStudy,positions_title
0,hydros achipravalappil,Oil & Energy,[Mechanical Maintenance Engineer ],S.O.S Consultants,Rotating Equipments in Oil & Gas Industry Stat...,Bachelor of Engineering (B.E.),Mechanical Engineering,[Mechanical Maintenance Engineer ]
1,Hasnaa ACHIQ,Construction,[Contrôleur de gestion opérationnel Départemen...,"Cegelec,Cegelec,SEFIN Holding",Reporting & Analysis SAP Financial Control Bud...,Mastère spécialisé Cycle normal d'école de com...,"Audit, contrôle de gestion et systèmes d'infor...",[Contrôleur de gestion opérationnel Départemen...
2,Ali Achir,Public Relations and Communications,"[Student, Customer Service Officer, Customer S...","Hassan II University,Metlife-Alico,Mashreq Bank",Event Planning Teamwork Customer Relations Neg...,M.S Management de la Communication des Organis...,Communication,"[Student, Customer Service Officer, Customer S..."
3,Nadjib Achir,Education Management,"[Researcher, PHD Student ]","Université Paris 13 Nord,University of Paris 6",Wireless Sensor Networks Wireless QoS,nan,,"[Researcher, PHD Student ]"
4,Meguru Achira,Pharmaceuticals,"[Group Manager, Head of PK/PD Science Group ]",Janssen Pharmaceutical K.K.,Pharmacokinetics DMPK Clinical Development Pha...,"MS, Ph.D.",Pharmacokinetics Pharmacokinetics,"[Group Manager, Head of PK/PD Science Group ]"

In [175]:
New_analyse_df = df__analyse_2.iloc[:,:7]
New_analyse_df.head()

,Name,Industry,positions__title,Company_Names,Skills_new,Degrees_new,FieldOfStudy
0,hydros achipravalappil,Oil & Energy,[Mechanical Maintenance Engineer ],S.O.S Consultants,Rotating Equipments in Oil & Gas Industry Stat...,Bachelor of Engineering (B.E.),Mechanical Engineering
1,Hasnaa ACHIQ,Construction,[Contrôleur de gestion opérationnel Départemen...,"Cegelec,Cegelec,SEFIN Holding",Reporting & Analysis SAP Financial Control Bud...,Mastère spécialisé Cycle normal d'école de com...,"Audit, contrôle de gestion et systèmes d'infor..."
2,Ali Achir,Public Relations and Communications,"[Student, Customer Service Officer, Customer S...","Hassan II University,Metlife-Alico,Mashreq Bank",Event Planning Teamwork Customer Relations Neg...,M.S Management de la Communication des Organis...,Communication
3,Nadjib Achir,Education Management,"[Researcher, PHD Student ]","Université Paris 13 Nord,University of Paris 6",Wireless Sensor Networks Wireless QoS,nan,
4,Meguru Achira,Pharmaceuticals,"[Group Manager, Head of PK/PD Science Group ]",Janssen Pharmaceutical K.K.,Pharmacokinetics DMPK Clinical Development Pha...,"MS, Ph.D.",Pharmacokinetics Pharmacokinetics

In [158]:
def splitInto_Separate_list(data_frame, 
                       column_split,
                      typ):
    
    #Accepts a column with multiple types and splits list variables to several rows.

    data_frame = data_frame
    column_split = column_split
    typ =typ
    
    
    row_accumulator = []

    def split_list_to_rows(row):
        SplitRow_by_column = row[column_split]
        if isinstance(SplitRow_by_column, list):
            for s in SplitRow_by_column:
                newR = row.to_dict()
                newR[column_split] = typ(s)
                row_accumulator.append(newR)
        else:
            newR = row.to_dict()
            newR[column_split] = typ(SplitRow_by_column)
            row_accumulator.append(newR)
  
    data_frame.apply(split_list_to_rows, axis=1)
    new_df = pd.DataFrame(row_accumulator)
  
    return new_df

Dataframe Separated with ', ' values on positions generated

In [179]:
df_split_separate_test = splitInto_Separate_list(New_analyse_df,'positions__title',str)
df_split_separate_test.head()

,Company_Names,Degrees_new,FieldOfStudy,Industry,Name,Skills_new,positions__title
0,S.O.S Consultants,Bachelor of Engineering (B.E.),Mechanical Engineering,Oil & Energy,hydros achipravalappil,Rotating Equipments in Oil & Gas Industry Stat...,Mechanical Maintenance Engineer
1,"Cegelec,Cegelec,SEFIN Holding",Mastère spécialisé Cycle normal d'école de com...,"Audit, contrôle de gestion et systèmes d'infor...",Construction,Hasnaa ACHIQ,Reporting & Analysis SAP Financial Control Bud...,Contrôleur de gestion opérationnel Département
2,"Cegelec,Cegelec,SEFIN Holding",Mastère spécialisé Cycle normal d'école de com...,"Audit, contrôle de gestion et systèmes d'infor...",Construction,Hasnaa ACHIQ,Reporting & Analysis SAP Financial Control Bud...,Contrôleur de gestion opérationnel Projet
3,"Cegelec,Cegelec,SEFIN Holding",Mastère spécialisé Cycle normal d'école de com...,"Audit, contrôle de gestion et systèmes d'infor...",Construction,Hasnaa ACHIQ,Reporting & Analysis SAP Financial Control Bud...,Stagiaire en Finances et comptabilité
4,"Hassan II University,Metlife-Alico,Mashreq Bank",M.S Management de la Communication des Organis...,Communication,Public Relations and Communications,Ali Achir,Event Planning Teamwork Customer Relations Neg...,Student

In [180]:
df_split_separate_test.shape

(483, 7)

In [188]:

#positions_split on , 
split_Company_Names =[]
posit_array = []
for coms in df_split_separate_test['Company_Names']:
    each_row = coms.split(",")
    split_Company_Names.append(each_row)
    del each_row
#print(split_Company_Names)

In [192]:
datafr_split_com_names = pd.Series(split_Company_Names)
#datafr_split_com_names.head()
New_datafr_split_coms = pd.DataFrame(datafr_split_com_names)

df_split_separate_test['Company_Names'] = New_datafr_split_coms
df_split_separate_test.head()

,Company_Names,Degrees_new,FieldOfStudy,Industry,Name,Skills_new,positions__title
0,[S.O.S Consultants ],Bachelor of Engineering (B.E.),Mechanical Engineering,Oil & Energy,hydros achipravalappil,Rotating Equipments in Oil & Gas Industry Stat...,Mechanical Maintenance Engineer
1,"[Cegelec, Cegelec, SEFIN Holding]",Mastère spécialisé Cycle normal d'école de com...,"Audit, contrôle de gestion et systèmes d'infor...",Construction,Hasnaa ACHIQ,Reporting & Analysis SAP Financial Control Bud...,Contrôleur de gestion opérationnel Département
2,"[Cegelec, Cegelec, SEFIN Holding]",Mastère spécialisé Cycle normal d'école de com...,"Audit, contrôle de gestion et systèmes d'infor...",Construction,Hasnaa ACHIQ,Reporting & Analysis SAP Financial Control Bud...,Contrôleur de gestion opérationnel Projet
3,"[Cegelec, Cegelec, SEFIN Holding]",Mastère spécialisé Cycle normal d'école de com...,"Audit, contrôle de gestion et systèmes d'infor...",Construction,Hasnaa ACHIQ,Reporting & Analysis SAP Financial Control Bud...,Stagiaire en Finances et comptabilité
4,"[Hassan II University, Metlife-Alico, Mashreq ...",M.S Management de la Communication des Organis...,Communication,Public Relations and Communications,Ali Achir,Event Planning Teamwork Customer Relations Neg...,Student

Dataframe Separated with ', ' values on Company names generated

In [193]:
df_split_separate_test_after_company = splitInto_Separate_list(df_split_separate_test,'Company_Names',str)
df_split_separate_test_after_company.head()

,Company_Names,Degrees_new,FieldOfStudy,Industry,Name,Skills_new,positions__title
0,S.O.S Consultants,Bachelor of Engineering (B.E.),Mechanical Engineering,Oil & Energy,hydros achipravalappil,Rotating Equipments in Oil & Gas Industry Stat...,Mechanical Maintenance Engineer
1,Cegelec,Mastère spécialisé Cycle normal d'école de com...,"Audit, contrôle de gestion et systèmes d'infor...",Construction,Hasnaa ACHIQ,Reporting & Analysis SAP Financial Control Bud...,Contrôleur de gestion opérationnel Département
2,Cegelec,Mastère spécialisé Cycle normal d'école de com...,"Audit, contrôle de gestion et systèmes d'infor...",Construction,Hasnaa ACHIQ,Reporting & Analysis SAP Financial Control Bud...,Contrôleur de gestion opérationnel Département
3,SEFIN Holding,Mastère spécialisé Cycle normal d'école de com...,"Audit, contrôle de gestion et systèmes d'infor...",Construction,Hasnaa ACHIQ,Reporting & Analysis SAP Financial Control Bud...,Contrôleur de gestion opérationnel Département
4,Cegelec,Mastère spécialisé Cycle normal d'école de com...,"Audit, contrôle de gestion et systèmes d'infor...",Construction,Hasnaa ACHIQ,Reporting & Analysis SAP Financial Control Bud...,Contrôleur de gestion opérationnel Projet

In [194]:
df_split_separate_test_after_company.shape

(1391, 7)

#combining position_company_title_Industry

In [203]:


df_split_separate_test_after_company['position_company_title'] = df_split_separate_test_after_company.positions__title.astype(str).str.cat(df_split_separate_test_after_company.Company_Names.astype(str), sep=' ')

#df_split_separate_test_after_company.drop(df_split_separate_test_after_company.position_company_titles)
New_combine_comp_pos_indus = df_split_separate_test_after_company[['Company_Names','Degrees_new','FieldOfStudy','Industry','Name','Skills_new','positions__title','position_company_title']]
New_combine_comp_pos_indus.head()

,Company_Names,Degrees_new,FieldOfStudy,Industry,Name,Skills_new,positions__title,position_company_title
0,S.O.S Consultants,Bachelor of Engineering (B.E.),Mechanical Engineering,Oil & Energy,hydros achipravalappil,Rotating Equipments in Oil & Gas Industry Stat...,Mechanical Maintenance Engineer,Mechanical Maintenance Engineer S.O.S Consult...
1,Cegelec,Mastère spécialisé Cycle normal d'école de com...,"Audit, contrôle de gestion et systèmes d'infor...",Construction,Hasnaa ACHIQ,Reporting & Analysis SAP Financial Control Bud...,Contrôleur de gestion opérationnel Département,Contrôleur de gestion opérationnel Département...
2,Cegelec,Mastère spécialisé Cycle normal d'école de com...,"Audit, contrôle de gestion et systèmes d'infor...",Construction,Hasnaa ACHIQ,Reporting & Analysis SAP Financial Control Bud...,Contrôleur de gestion opérationnel Département,Contrôleur de gestion opérationnel Département...
3,SEFIN Holding,Mastère spécialisé Cycle normal d'école de com...,"Audit, contrôle de gestion et systèmes d'infor...",Construction,Hasnaa ACHIQ,Reporting & Analysis SAP Financial Control Bud...,Contrôleur de gestion opérationnel Département,Contrôleur de gestion opérationnel Département...
4,Cegelec,Mastère spécialisé Cycle normal d'école de com...,"Audit, contrôle de gestion et systèmes d'infor...",Construction,Hasnaa ACHIQ,Reporting & Analysis SAP Financial Control Bud...,Contrôleur de gestion opérationnel Projet,Contrôleur de gestion opérationnel Projet Cegelec

#combining Degrees_new_FieldOfStudy_Skills_new

In [296]:
#New_combine_comp_pos_indus['Degrees_new_FieldOfStudy_Skills_new'] = New_combine_comp_pos_indus.Skills_new.astype(str).str.cat(New_combine_comp_pos_indus.FieldOfStudy.astype(str), sep=' ').str.cat(New_combine_comp_pos_indus.Degrees_new.astype(str), sep=' ').str.cat(New_combine_comp_pos_indus.Industry.astype(str), sep=' ')
#New_combine_comp_pos_indus.head()
N = len(New_combine_comp_pos_indus.Degrees_new_FieldOfStudy_Skills_new)
print(N)
S1 = New_combine_comp_pos_indus['Degrees_new_FieldOfStudy_Skills_new']
S2 = New_combine_comp_pos_indus['positions__title']
N = len(New_combine_comp_pos_indus.Degrees_new_FieldOfStudy_Skills_new)
N2 = len(S2)
print(N2)

1391
1391

In [297]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
d = np.zeros((N+2,N+2))
matrix_skill = pd.DataFrame(d)
count_i = 0 

for i in S1:
    count_j = 0 
    matrix_skill.iloc[count_i,count_j] = i
    #print("This is the first one"+ matrix.iloc[count_i,count_j])
    
    #print(i)
   
    bow_i = i.split(" ")
    
    for j in S1:
        count_j +=1
        
        #print(j)

        train_set = [i,j]

        tfidf_vectorizer = TfidfVectorizer()
        tfidf_matrix_train = tfidf_vectorizer.fit_transform(train_set)  #finds the tfidf score with normalization
        cosine_scores = cosine_similarity(tfidf_matrix_train[0:1], tfidf_matrix_train)
        matrix_skill.iloc[count_i,count_j] = cosine_scores[:,1]
    print("values of i completed:")
    print(count_i)
    count_i += 1

print(matrix_pos_com)
print("Printing first 10 similarity values for Degrees_new_FieldOfStudy_Skills_new:")  
print(matrix_skill)

values of i completed:
0
values of i completed:
1
values of i completed:
2
values of i completed:
3
values of i completed:
4
values of i completed:
5
values of i completed:
6
values of i completed:
7
values of i completed:
8
values of i completed:
9
values of i completed:
10
values of i completed:
11
values of i completed:
12
values of i completed:
13
values of i completed:
14
values of i completed:
15
values of i completed:
16
values of i completed:
17
values of i completed:
18
values of i completed:
19
values of i completed:
20
values of i completed:
21
values of i completed:
22
values of i completed:
23
values of i completed:
24
values of i completed:
25
values of i completed:
26
values of i completed:
27
values of i completed:
28
values of i completed:
29
values of i completed:
30
values of i completed:
31
values of i completed:
32
values of i completed:
33
values of i completed:
34
values of i completed:
35
values of i completed:
36
values of i completed:
37
values of i completed:
38
values of i completed:
39
values of i completed:
40
values of i completed:
41
values of i completed:
42
values of i completed:
43
values of i completed:
44
values of i completed:
45
values of i completed:
46
values of i completed:
47
values of i completed:
48
values of i completed:
49
values of i completed:
50
values of i completed:
51
values of i completed:
52
values of i completed:
53
values of i completed:
54
values of i completed:
55
values of i completed:
56
values of i completed:
57
values of i completed:
58
values of i completed:
59
values of i completed:
60
values of i completed:
61
values of i completed:
62
values of i completed:
63
values of i completed:
64
values of i completed:
65
values of i completed:
66
values of i completed:
67
values of i completed:
68
values of i completed:
69
values of i completed:
70
values of i completed:
71
values of i completed:
72
values of i completed:
73
values of i completed:
74
values of i completed:
75
values of i completed:
76
values of i completed:
77
values of i completed:
78
values of i completed:
79
values of i completed:
80
values of i completed:
81
values of i completed:
82
values of i completed:
83
values of i completed:
84
values of i completed:
85
values of i completed:
86
values of i completed:
87
values of i completed:
88
values of i completed:
89
values of i completed:
90
values of i completed:
91
values of i completed:
92
values of i completed:
93
values of i completed:
94
values of i completed:
95
values of i completed:
96
values of i completed:
97
values of i completed:
98
values of i completed:
99
values of i completed:
100
values of i completed:
101
values of i completed:
102
values of i completed:
103
values of i completed:
104
values of i completed:
105
values of i completed:
106
values of i completed:
107
values of i completed:
108
values of i completed:
109
values of i completed:
110
values of i completed:
111
values of i completed:
112
values of i completed:
113
values of i completed:
114
values of i completed:
115
values of i completed:
116
values of i completed:
117
values of i completed:
118
values of i completed:
119
values of i completed:
120
values of i completed:
121
values of i completed:
122
values of i completed:
123
values of i completed:
124
values of i completed:
125
values of i completed:
126
values of i completed:
127
values of i completed:
128
values of i completed:
129
values of i completed:
130
values of i completed:
131
values of i completed:
132
values of i completed:
133
values of i completed:
134
values of i completed:
135
values of i completed:
136
values of i completed:
137
values of i completed:
138
values of i completed:
139
values of i completed:
140
values of i completed:
141
values of i completed:
142
values of i completed:
143
values of i completed:
144
values of i completed:
145
values of i completed:
146
values of i completed:
147
values of i completed:
148
values of i completed:
149
values of i completed:
150
values of i completed:
151
values of i completed:
152
values of i completed:
153
values of i completed:
154
values of i completed:
155
values of i completed:
156
values of i completed:
157
values of i completed:
158
values of i completed:
159
values of i completed:
160
values of i completed:
161
values of i completed:
162
values of i completed:
163
values of i completed:
164
values of i completed:
165
values of i completed:
166
values of i completed:
167
values of i completed:
168
values of i completed:
169
values of i completed:
170
values of i completed:
171
values of i completed:
172
values of i completed:
173
values of i completed:
174
values of i completed:
175
values of i completed:
176
values of i completed:
177
values of i completed:
178
values of i completed:
179
values of i completed:
180
values of i completed:
181
values of i completed:
182
values of i completed:
183
values of i completed:
184
values of i completed:
185
values of i completed:
186
values of i completed:
187
values of i completed:
188
values of i completed:
189
values of i completed:
190
values of i completed:
191
values of i completed:
192
values of i completed:
193
values of i completed:
194
values of i completed:
195
values of i completed:
196
values of i completed:
197
values of i completed:
198
values of i completed:
199
values of i completed:
200
values of i completed:
201
values of i completed:
202
values of i completed:
203
values of i completed:
204
values of i completed:
205
values of i completed:
206
values of i completed:
207
values of i completed:
208
values of i completed:
209
values of i completed:
210
values of i completed:
211
values of i completed:
212
values of i completed:
213
values of i completed:
214
values of i completed:
215
values of i completed:
216
values of i completed:
217
values of i completed:
218
values of i completed:
219
values of i completed:
220
values of i completed:
221
values of i completed:
222
values of i completed:
223
values of i completed:
224
values of i completed:
225
values of i completed:
226
values of i completed:
227
values of i completed:
228
values of i completed:
229
values of i completed:
230
values of i completed:
231
values of i completed:
232
values of i completed:
233
values of i completed:
234
values of i completed:
235
values of i completed:
236
values of i completed:
237
values of i completed:
238
values of i completed:
239
values of i completed:
240
values of i completed:
241
values of i completed:
242
values of i completed:
243
values of i completed:
244
values of i completed:
245
values of i completed:
246
values of i completed:
247
values of i completed:
248
values of i completed:
249
values of i completed:
250
values of i completed:
251
values of i completed:
252
values of i completed:
253
values of i completed:
254
values of i completed:
255
values of i completed:
256
values of i completed:
257
values of i completed:
258
values of i completed:
259
values of i completed:
260
values of i completed:
261
values of i completed:
262
values of i completed:
263
values of i completed:
264
values of i completed:
265
values of i completed:
266
values of i completed:
267
values of i completed:
268
values of i completed:
269
values of i completed:
270
values of i completed:
271
values of i completed:
272
values of i completed:
273
values of i completed:
274
values of i completed:
275
values of i completed:
276
values of i completed:
277
values of i completed:
278
values of i completed:
279
values of i completed:
280
values of i completed:
281
values of i completed:
282
values of i completed:
283
values of i completed:
284
values of i completed:
285
values of i completed:
286
values of i completed:
287
values of i completed:
288
values of i completed:
289
values of i completed:
290
values of i completed:
291
values of i completed:
292
values of i completed:
293
values of i completed:
294
values of i completed:
295
values of i completed:
296
values of i completed:
297
values of i completed:
298
values of i completed:
299
values of i completed:
300
values of i completed:
301
values of i completed:
302
values of i completed:
303
values of i completed:
304
values of i completed:
305
values of i completed:
306
values of i completed:
307

values of i completed:
308
values of i completed:
309
values of i completed:
310
values of i completed:
311
values of i completed:
312
values of i completed:
313
values of i completed:
314
values of i completed:
315
values of i completed:
316
values of i completed:
317
values of i completed:
318
values of i completed:
319
values of i completed:
320
values of i completed:
321
values of i completed:
322
values of i completed:
323
values of i completed:
324
values of i completed:
325
values of i completed:
326
values of i completed:
327
values of i completed:
328
values of i completed:
329
values of i completed:
330
values of i completed:
331
values of i completed:
332
values of i completed:
333
values of i completed:
334
values of i completed:
335
values of i completed:
336
values of i completed:
337
values of i completed:
338
values of i completed:
339
values of i completed:
340
values of i completed:
341
values of i completed:
342
values of i completed:
343
values of i completed:
344
values of i completed:
345
values of i completed:
346
values of i completed:
347
values of i completed:
348
values of i completed:
349
values of i completed:
350
values of i completed:
351
values of i completed:
352
values of i completed:
353
values of i completed:
354
values of i completed:
355
values of i completed:
356
values of i completed:
357
values of i completed:
358
values of i completed:
359
values of i completed:
360
values of i completed:
361
values of i completed:
362
values of i completed:
363
values of i completed:
364
values of i completed:
365
values of i completed:
366
values of i completed:
367
values of i completed:
368
values of i completed:
369
values of i completed:
370
values of i completed:
371
values of i completed:
372
values of i completed:
373
values of i completed:
374
values of i completed:
375
values of i completed:
376
values of i completed:
377
values of i completed:
378
values of i completed:
379
values of i completed:
380
values of i completed:
381
values of i completed:
382
values of i completed:
383
values of i completed:
384
values of i completed:
385
values of i completed:
386
values of i completed:
387
values of i completed:
388
values of i completed:
389
values of i completed:
390
values of i completed:
391
values of i completed:
392
values of i completed:
393
values of i completed:
394
values of i completed:
395
values of i completed:
396
values of i completed:
397
values of i completed:
398
values of i completed:
399
values of i completed:
400
values of i completed:
401
values of i completed:
402
values of i completed:
403
values of i completed:
404
values of i completed:
405
values of i completed:
406
values of i completed:
407
values of i completed:
408
values of i completed:
409
values of i completed:
410
values of i completed:
411
values of i completed:
412
values of i completed:
413
values of i completed:
414
values of i completed:
415
values of i completed:
416
values of i completed:
417
values of i completed:
418
values of i completed:
419
values of i completed:
420
values of i completed:
421
values of i completed:
422
values of i completed:
423
values of i completed:
424
values of i completed:
425
values of i completed:
426
values of i completed:
427
values of i completed:
428
values of i completed:
429
values of i completed:
430
values of i completed:
431
values of i completed:
432
values of i completed:
433
values of i completed:
434
values of i completed:
435
values of i completed:
436
values of i completed:
437
values of i completed:
438
values of i completed:
439
values of i completed:
440
values of i completed:
441
values of i completed:
442
values of i completed:
443
values of i completed:
444
values of i completed:
445
values of i completed:
446
values of i completed:
447
values of i completed:
448
values of i completed:
449
values of i completed:
450
values of i completed:
451
values of i completed:
452
values of i completed:
453
values of i completed:
454
values of i completed:
455
values of i completed:
456
values of i completed:
457
values of i completed:
458
values of i completed:
459
values of i completed:
460
values of i completed:
461
values of i completed:
462
values of i completed:
463
values of i completed:
464
values of i completed:
465
values of i completed:
466
values of i completed:
467
values of i completed:
468
values of i completed:
469
values of i completed:
470
values of i completed:
471
values of i completed:
472
values of i completed:
473
values of i completed:
474
values of i completed:
475
values of i completed:
476
values of i completed:
477
values of i completed:
478
values of i completed:
479
values of i completed:
480
values of i completed:
481
values of i completed:
482
values of i completed:
483
values of i completed:
484
values of i completed:
485
values of i completed:
486
values of i completed:
487
values of i completed:
488
values of i completed:
489
values of i completed:
490
values of i completed:
491
values of i completed:
492
values of i completed:
493
values of i completed:
494
values of i completed:
495
values of i completed:
496
values of i completed:
497
values of i completed:
498
values of i completed:
499
values of i completed:
500
values of i completed:
501
values of i completed:
502
values of i completed:
503
values of i completed:
504
values of i completed:
505
values of i completed:
506
values of i completed:
507
values of i completed:
508
values of i completed:
509
values of i completed:
510
values of i completed:
511
values of i completed:
512
values of i completed:
513
values of i completed:
514
values of i completed:
515
values of i completed:
516
values of i completed:
517
values of i completed:
518
values of i completed:
519
values of i completed:
520
values of i completed:
521
values of i completed:
522
values of i completed:
523
values of i completed:
524
values of i completed:
525
values of i completed:
526
values of i completed:
527
values of i completed:
528
values of i completed:
529
values of i completed:
530
values of i completed:
531
values of i completed:
532
values of i completed:
533
values of i completed:
534
values of i completed:
535
values of i completed:
536
values of i completed:
537
values of i completed:
538
values of i completed:
539
values of i completed:
540
values of i completed:
541
values of i completed:
542
values of i completed:
543
values of i completed:
544
values of i completed:
545
values of i completed:
546
values of i completed:
547
values of i completed:
548
values of i completed:
549
values of i completed:
550
values of i completed:
551
values of i completed:
552
values of i completed:
553
values of i completed:
554
values of i completed:
555
values of i completed:
556
values of i completed:
557
values of i completed:
558
values of i completed:
559
values of i completed:
560
values of i completed:
561
values of i completed:
562
values of i completed:
563
values of i completed:
564
values of i completed:
565
values of i completed:
566
values of i completed:
567
values of i completed:
568
values of i completed:
569
values of i completed:
570
values of i completed:
571
values of i completed:
572
values of i completed:
573
values of i completed:
574
values of i completed:
575
values of i completed:
576
values of i completed:
577
values of i completed:
578
values of i completed:
579
values of i completed:
580
values of i completed:
581
values of i completed:
582
values of i completed:
583
values of i completed:
584
values of i completed:
585
values of i completed:
586
values of i completed:
587
values of i completed:
588
values of i completed:
589
values of i completed:
590
values of i completed:
591
values of i completed:
592
values of i completed:
593
values of i completed:
594
values of i completed:
595
values of i completed:
596
values of i completed:
597
values of i completed:
598
values of i completed:
599
values of i completed:
600
values of i completed:
601
values of i completed:
602
values of i completed:
603
values of i completed:
604
values of i completed:
605
values of i completed:
606
values of i completed:
607
values of i completed:
608
values of i completed:
609
values of i completed:
610
values of i completed:
611

values of i completed:
612
values of i completed:
613
values of i completed:
614
values of i completed:
615
values of i completed:
616
values of i completed:
617
values of i completed:
618
values of i completed:
619
values of i completed:
620
values of i completed:
621
values of i completed:
622
values of i completed:
623
values of i completed:
624
values of i completed:
625
values of i completed:
626
values of i completed:
627
values of i completed:
628
values of i completed:
629
values of i completed:
630
values of i completed:
631
values of i completed:
632
values of i completed:
633
values of i completed:
634
values of i completed:
635
values of i completed:
636
values of i completed:
637
values of i completed:
638
values of i completed:
639
values of i completed:
640
values of i completed:
641
values of i completed:
642
values of i completed:
643
values of i completed:
644
values of i completed:
645
values of i completed:
646
values of i completed:
647
values of i completed:
648
values of i completed:
649
values of i completed:
650
values of i completed:
651
values of i completed:
652
values of i completed:
653
values of i completed:
654
values of i completed:
655
values of i completed:
656
values of i completed:
657
values of i completed:
658
values of i completed:
659
values of i completed:
660
values of i completed:
661
values of i completed:
662
values of i completed:
663
values of i completed:
664
values of i completed:
665
values of i completed:
666
values of i completed:
667
values of i completed:
668
values of i completed:
669
values of i completed:
670
values of i completed:
671
values of i completed:
672
values of i completed:
673
values of i completed:
674
values of i completed:
675
values of i completed:
676
values of i completed:
677
values of i completed:
678
values of i completed:
679
values of i completed:
680
values of i completed:
681
values of i completed:
682
values of i completed:
683
values of i completed:
684
values of i completed:
685
values of i completed:
686
values of i completed:
687
values of i completed:
688
values of i completed:
689
values of i completed:
690
values of i completed:
691
values of i completed:
692
values of i completed:
693
values of i completed:
694
values of i completed:
695
values of i completed:
696
values of i completed:
697
values of i completed:
698
values of i completed:
699
values of i completed:
700
values of i completed:
701
values of i completed:
702
values of i completed:
703
values of i completed:
704
values of i completed:
705
values of i completed:
706
values of i completed:
707
values of i completed:
708
values of i completed:
709
values of i completed:
710
values of i completed:
711
values of i completed:
712
values of i completed:
713
values of i completed:
714
values of i completed:
715
values of i completed:
716
values of i completed:
717
values of i completed:
718
values of i completed:
719
values of i completed:
720
values of i completed:
721
values of i completed:
722
values of i completed:
723
values of i completed:
724
values of i completed:
725
values of i completed:
726
values of i completed:
727
values of i completed:
728
values of i completed:
729
values of i completed:
730
values of i completed:
731
values of i completed:
732
values of i completed:
733
values of i completed:
734
values of i completed:
735
values of i completed:
736
values of i completed:
737
values of i completed:
738
values of i completed:
739
values of i completed:
740
values of i completed:
741
values of i completed:
742
values of i completed:
743
values of i completed:
744
values of i completed:
745
values of i completed:
746
values of i completed:
747
values of i completed:
748
values of i completed:
749
values of i completed:
750
values of i completed:
751
values of i completed:
752
values of i completed:
753
values of i completed:
754
values of i completed:
755
values of i completed:
756
values of i completed:
757
values of i completed:
758
values of i completed:
759
values of i completed:
760
values of i completed:
761
values of i completed:
762
values of i completed:
763
values of i completed:
764
values of i completed:
765
values of i completed:
766
values of i completed:
767
values of i completed:
768
values of i completed:
769
values of i completed:
770
values of i completed:
771
values of i completed:
772
values of i completed:
773
values of i completed:
774
values of i completed:
775
values of i completed:
776
values of i completed:
777
values of i completed:
778
values of i completed:
779
values of i completed:
780
values of i completed:
781
values of i completed:
782
values of i completed:
783
values of i completed:
784
values of i completed:
785
values of i completed:
786
values of i completed:
787
values of i completed:
788
values of i completed:
789
values of i completed:
790
values of i completed:
791
values of i completed:
792
values of i completed:
793
values of i completed:
794
values of i completed:
795
values of i completed:
796
values of i completed:
797
values of i completed:
798
values of i completed:
799
values of i completed:
800
values of i completed:
801
values of i completed:
802
values of i completed:
803
values of i completed:
804
values of i completed:
805
values of i completed:
806
values of i completed:
807
values of i completed:
808
values of i completed:
809
values of i completed:
810
values of i completed:
811
values of i completed:
812
values of i completed:
813
values of i completed:
814
values of i completed:
815
values of i completed:
816
values of i completed:
817
values of i completed:
818
values of i completed:
819
values of i completed:
820
values of i completed:
821
values of i completed:
822
values of i completed:
823
values of i completed:
824
values of i completed:
825
values of i completed:
826
values of i completed:
827
values of i completed:
828
values of i completed:
829
values of i completed:
830
values of i completed:
831
values of i completed:
832
values of i completed:
833
values of i completed:
834
values of i completed:
835
values of i completed:
836
values of i completed:
837
values of i completed:
838
values of i completed:
839
values of i completed:
840
values of i completed:
841
values of i completed:
842
values of i completed:
843
values of i completed:
844
values of i completed:
845
values of i completed:
846
values of i completed:
847
values of i completed:
848
values of i completed:
849
values of i completed:
850
values of i completed:
851
values of i completed:
852
values of i completed:
853
values of i completed:
854
values of i completed:
855
values of i completed:
856
values of i completed:
857
values of i completed:
858
values of i completed:
859
values of i completed:
860
values of i completed:
861
values of i completed:
862
values of i completed:
863
values of i completed:
864
values of i completed:
865
values of i completed:
866
values of i completed:
867
values of i completed:
868
values of i completed:
869
values of i completed:
870
values of i completed:
871
values of i completed:
872
values of i completed:
873
values of i completed:
874
values of i completed:
875
values of i completed:
876
values of i completed:
877
values of i completed:
878
values of i completed:
879
values of i completed:
880
values of i completed:
881
values of i completed:
882
values of i completed:
883
values of i completed:
884
values of i completed:
885
values of i completed:
886
values of i completed:
887
values of i completed:
888
values of i completed:
889
values of i completed:
890
values of i completed:
891
values of i completed:
892
values of i completed:
893
values of i completed:
894
values of i completed:
895
values of i completed:
896
values of i completed:
897
values of i completed:
898
values of i completed:
899
values of i completed:
900
values of i completed:
901
values of i completed:
902
values of i completed:
903
values of i completed:
904
values of i completed:
905
values of i completed:
906
values of i completed:
907
values of i completed:
908
values of i completed:
909
values of i completed:
910
values of i completed:
911
values of i completed:
912
values of i completed:
913
values of i completed:
914
values of i completed:
915

values of i completed:
916
values of i completed:
917
values of i completed:
918
values of i completed:
919
values of i completed:
920
values of i completed:
921
values of i completed:
922
values of i completed:
923
values of i completed:
924
values of i completed:
925
values of i completed:
926
values of i completed:
927
values of i completed:
928
values of i completed:
929
values of i completed:
930
values of i completed:
931
values of i completed:
932
values of i completed:
933
values of i completed:
934
values of i completed:
935
values of i completed:
936
values of i completed:
937
values of i completed:
938
values of i completed:
939
values of i completed:
940
values of i completed:
941
values of i completed:
942
values of i completed:
943
values of i completed:
944
values of i completed:
945
values of i completed:
946
values of i completed:
947
values of i completed:
948
values of i completed:
949
values of i completed:
950
values of i completed:
951
values of i completed:
952
values of i completed:
953
values of i completed:
954
values of i completed:
955
values of i completed:
956
values of i completed:
957
values of i completed:
958
values of i completed:
959
values of i completed:
960
values of i completed:
961
values of i completed:
962
values of i completed:
963
values of i completed:
964
values of i completed:
965
values of i completed:
966
values of i completed:
967
values of i completed:
968
values of i completed:
969
values of i completed:
970
values of i completed:
971
values of i completed:
972
values of i completed:
973
values of i completed:
974
values of i completed:
975
values of i completed:
976
values of i completed:
977
values of i completed:
978
values of i completed:
979
values of i completed:
980
values of i completed:
981
values of i completed:
982
values of i completed:
983
values of i completed:
984
values of i completed:
985
values of i completed:
986
values of i completed:
987
values of i completed:
988
values of i completed:
989
values of i completed:
990
values of i completed:
991
values of i completed:
992
values of i completed:
993
values of i completed:
994
values of i completed:
995
values of i completed:
996
values of i completed:
997
values of i completed:
998
values of i completed:
999
values of i completed:
1000
values of i completed:
1001
values of i completed:
1002
values of i completed:
1003
values of i completed:
1004
values of i completed:
1005
values of i completed:
1006
values of i completed:
1007
values of i completed:
1008
values of i completed:
1009
values of i completed:
1010
values of i completed:
1011
values of i completed:
1012
values of i completed:
1013
values of i completed:
1014
values of i completed:
1015
values of i completed:
1016
values of i completed:
1017
values of i completed:
1018
values of i completed:
1019
values of i completed:
1020
values of i completed:
1021
values of i completed:
1022
values of i completed:
1023
values of i completed:
1024
values of i completed:
1025
values of i completed:
1026
values of i completed:
1027
values of i completed:
1028
values of i completed:
1029
values of i completed:
1030
values of i completed:
1031
values of i completed:
1032
values of i completed:
1033
values of i completed:
1034
values of i completed:
1035
values of i completed:
1036
values of i completed:
1037
values of i completed:
1038
values of i completed:
1039
values of i completed:
1040
values of i completed:
1041
values of i completed:
1042
values of i completed:
1043
values of i completed:
1044
values of i completed:
1045
values of i completed:
1046
values of i completed:
1047
values of i completed:
1048
values of i completed:
1049
values of i completed:
1050
values of i completed:
1051
values of i completed:
1052
values of i completed:
1053
values of i completed:
1054
values of i completed:
1055
values of i completed:
1056
values of i completed:
1057
values of i completed:
1058
values of i completed:
1059
values of i completed:
1060
values of i completed:
1061
values of i completed:
1062
values of i completed:
1063
values of i completed:
1064
values of i completed:
1065
values of i completed:
1066
values of i completed:
1067
values of i completed:
1068
values of i completed:
1069
values of i completed:
1070
values of i completed:
1071
values of i completed:
1072
values of i completed:
1073
values of i completed:
1074
values of i completed:
1075
values of i completed:
1076
values of i completed:
1077
values of i completed:
1078
values of i completed:
1079
values of i completed:
1080
values of i completed:
1081
values of i completed:
1082
values of i completed:
1083
values of i completed:
1084
values of i completed:
1085
values of i completed:
1086
values of i completed:
1087
values of i completed:
1088
values of i completed:
1089
values of i completed:
1090
values of i completed:
1091
values of i completed:
1092
values of i completed:
1093
values of i completed:
1094
values of i completed:
1095
values of i completed:
1096
values of i completed:
1097
values of i completed:
1098
values of i completed:
1099
values of i completed:
1100
values of i completed:
1101
values of i completed:
1102
values of i completed:
1103
values of i completed:
1104
values of i completed:
1105
values of i completed:
1106
values of i completed:
1107
values of i completed:
1108
values of i completed:
1109
values of i completed:
1110
values of i completed:
1111
values of i completed:
1112
values of i completed:
1113
values of i completed:
1114
values of i completed:
1115
values of i completed:
1116
values of i completed:
1117
values of i completed:
1118
values of i completed:
1119
values of i completed:
1120
values of i completed:
1121
values of i completed:
1122
values of i completed:
1123
values of i completed:
1124
values of i completed:
1125
values of i completed:
1126
values of i completed:
1127
values of i completed:
1128
values of i completed:
1129
values of i completed:
1130
values of i completed:
1131
values of i completed:
1132
values of i completed:
1133
values of i completed:
1134
values of i completed:
1135
values of i completed:
1136
values of i completed:
1137
values of i completed:
1138
values of i completed:
1139
values of i completed:
1140
values of i completed:
1141
values of i completed:
1142
values of i completed:
1143
values of i completed:
1144
values of i completed:
1145
values of i completed:
1146
values of i completed:
1147
values of i completed:
1148
values of i completed:
1149
values of i completed:
1150
values of i completed:
1151
values of i completed:
1152
values of i completed:
1153
values of i completed:
1154
values of i completed:
1155
values of i completed:
1156
values of i completed:
1157
values of i completed:
1158
values of i completed:
1159
values of i completed:
1160
values of i completed:
1161
values of i completed:
1162
values of i completed:
1163
values of i completed:
1164
values of i completed:
1165
values of i completed:
1166
values of i completed:
1167
values of i completed:
1168
values of i completed:
1169
values of i completed:
1170
values of i completed:
1171
values of i completed:
1172
values of i completed:
1173
values of i completed:
1174
values of i completed:
1175
values of i completed:
1176
values of i completed:
1177
values of i completed:
1178
values of i completed:
1179
values of i completed:
1180
values of i completed:
1181
values of i completed:
1182
values of i completed:
1183
values of i completed:
1184
values of i completed:
1185
values of i completed:
1186
values of i completed:
1187
values of i completed:
1188
values of i completed:
1189
values of i completed:
1190
values of i completed:
1191
values of i completed:
1192
values of i completed:
1193
values of i completed:
1194
values of i completed:
1195
values of i completed:
1196
values of i completed:
1197
values of i completed:
1198
values of i completed:
1199
values of i completed:
1200
values of i completed:
1201
values of i completed:
1202
values of i completed:
1203
values of i completed:
1204
values of i completed:
1205
values of i completed:
1206
values of i completed:
1207
values of i completed:
1208
values of i completed:
1209
values of i completed:
1210
values of i completed:
1211

values of i completed:
1212
values of i completed:
1213
values of i completed:
1214
values of i completed:
1215
values of i completed:
1216
values of i completed:
1217
values of i completed:
1218
values of i completed:
1219
values of i completed:
1220
values of i completed:
1221
values of i completed:
1222
values of i completed:
1223
values of i completed:
1224
values of i completed:
1225
values of i completed:
1226
values of i completed:
1227
values of i completed:
1228
values of i completed:
1229
values of i completed:
1230
values of i completed:
1231
values of i completed:
1232
values of i completed:
1233
values of i completed:
1234
values of i completed:
1235
values of i completed:
1236
values of i completed:
1237
values of i completed:
1238
values of i completed:
1239
values of i completed:
1240
values of i completed:
1241
values of i completed:
1242
values of i completed:
1243
values of i completed:
1244
values of i completed:
1245
values of i completed:
1246
values of i completed:
1247
values of i completed:
1248
values of i completed:
1249
values of i completed:
1250
values of i completed:
1251
values of i completed:
1252
values of i completed:
1253
values of i completed:
1254
values of i completed:
1255
values of i completed:
1256
values of i completed:
1257
values of i completed:
1258
values of i completed:
1259
values of i completed:
1260
values of i completed:
1261
values of i completed:
1262
values of i completed:
1263
values of i completed:
1264
values of i completed:
1265
values of i completed:
1266
values of i completed:
1267
values of i completed:
1268
values of i completed:
1269
values of i completed:
1270
values of i completed:
1271
values of i completed:
1272
values of i completed:
1273
values of i completed:
1274
values of i completed:
1275
values of i completed:
1276
values of i completed:
1277
values of i completed:
1278
values of i completed:
1279
values of i completed:
1280
values of i completed:
1281
values of i completed:
1282
values of i completed:
1283
values of i completed:
1284
values of i completed:
1285
values of i completed:
1286
values of i completed:
1287
values of i completed:
1288
values of i completed:
1289
values of i completed:
1290
values of i completed:
1291
values of i completed:
1292
values of i completed:
1293
values of i completed:
1294
values of i completed:
1295
values of i completed:
1296
values of i completed:
1297
values of i completed:
1298
values of i completed:
1299
values of i completed:
1300
values of i completed:
1301
values of i completed:
1302
values of i completed:
1303
values of i completed:
1304
values of i completed:
1305
values of i completed:
1306
values of i completed:
1307
values of i completed:
1308
values of i completed:
1309
values of i completed:
1310
values of i completed:
1311
values of i completed:
1312
values of i completed:
1313
values of i completed:
1314
values of i completed:
1315
values of i completed:
1316
values of i completed:
1317
values of i completed:
1318
values of i completed:
1319
values of i completed:
1320
values of i completed:
1321
values of i completed:
1322
values of i completed:
1323
values of i completed:
1324
values of i completed:
1325
values of i completed:
1326
values of i completed:
1327
values of i completed:
1328
values of i completed:
1329
values of i completed:
1330
values of i completed:
1331
values of i completed:
1332
values of i completed:
1333
values of i completed:
1334
values of i completed:
1335
values of i completed:
1336
values of i completed:
1337
values of i completed:
1338
values of i completed:
1339
values of i completed:
1340
values of i completed:
1341
values of i completed:
1342
values of i completed:
1343
values of i completed:
1344
values of i completed:
1345
values of i completed:
1346
values of i completed:
1347
values of i completed:
1348
values of i completed:
1349
values of i completed:
1350
values of i completed:
1351
values of i completed:
1352
values of i completed:
1353
values of i completed:
1354
values of i completed:
1355
values of i completed:
1356
values of i completed:
1357
values of i completed:
1358
values of i completed:
1359
values of i completed:
1360
values of i completed:
1361
values of i completed:
1362
values of i completed:
1363
values of i completed:
1364
values of i completed:
1365
values of i completed:
1366
values of i completed:
1367
values of i completed:
1368
values of i completed:
1369
values of i completed:
1370
values of i completed:
1371
values of i completed:
1372
values of i completed:
1373
values of i completed:
1374
values of i completed:
1375
values of i completed:
1376
values of i completed:
1377
values of i completed:
1378
values of i completed:
1379
values of i completed:
1380
values of i completed:
1381
values of i completed:
1382
values of i completed:
1383
values of i completed:
1384
values of i completed:
1385
values of i completed:
1386
values of i completed:
1387
values of i completed:
1388
values of i completed:
1389
values of i completed:
1390
                                                0     1         2     \
0                   Mechanical Maintenance Engineer    0.0  0.000000
1     Contrôleur de gestion opérationnel Département   1.0  0.000000
2     Contrôleur de gestion opérationnel Département   0.0  1.000000
3     Contrôleur de gestion opérationnel Département   0.0  1.000000
4          Contrôleur de gestion opérationnel Projet   0.0  1.000000
5          Contrôleur de gestion opérationnel Projet   0.0  0.669419
6          Contrôleur de gestion opérationnel Projet   0.0  0.669419
7              Stagiaire en Finances et comptabilité   0.0  0.669419
8              Stagiaire en Finances et comptabilité   0.0  0.000000
9              Stagiaire en Finances et comptabilité   0.0  0.000000
10                                                 0   0.0  0.000000
11                                                 0   0.0  0.000000
12                                                 0   0.0  0.000000
13                                                 0   0.0  0.000000
14                                                 0   0.0  0.000000
15                                                 0   0.0  0.000000
16                                                 0   0.0  0.000000
17                                                 0   0.0  0.000000
18                                                 0   0.0  0.000000
19                                                 0   0.0  0.000000
20                                                 0   0.0  0.000000
21                                                 0   0.0  0.000000
22                                                 0   0.0  0.000000
23                                                 0   0.0  0.000000
24                                                 0   0.0  0.000000
25                                                 0   0.0  0.000000
26                                                 0   0.0  0.000000
27                                                 0   0.0  0.000000
28                                                 0   0.0  0.000000
29                                                 0   0.0  0.000000
...                                              ...   ...       ...
1363                                               0   0.0  0.000000
1364                                               0   0.0  0.000000
1365                                               0   0.0  0.000000
1366                                               0   0.0  0.000000
1367                                               0   0.0  0.000000
1368                                               0   0.0  0.000000
1369                                               0   0.0  0.000000
1370                                               0   0.0  0.000000
1371                                               0   0.0  0.000000
1372                                               0   0.0  0.000000
1373                                               0   0.0  0.000000
1374                                               0   0.0  0.000000
1375                                               0   0.0  0.000000
1376                                               0   0.0  0.000000
1377                                               0   0.0  0.000000
1378                                               0   0.0  0.000000
1379                                               0   0.0  0.000000
1380                                               0   0.0  0.000000
1381                                               0   0.0  0.000000
1382                                               0   0.0  0.000000
1383                                               0   0.0  0.000000
1384                                               0   0.0  0.000000
1385                                               0   0.0  0.000000
1386                                               0   0.0  0.000000
1387                                               0   0.0  0.000000
1388                                               0   0.0  0.000000
1389                                               0   0.0  0.000000
1390                                               0   0.0  0.000000
1391                                               0   0.0  0.000000
1392                                               0   0.0  0.000000

          3         4         5         6         7     8     9     ...   \
0     0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1     0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
2     1.000000  1.000000  0.669419  0.669419  0.669419   0.0   0.0  ...
3     1.000000  1.000000  0.669419  0.669419  0.669419   0.0   0.0  ...
4     1.000000  1.000000  0.669419  0.669419  0.669419   0.0   0.0  ...
5     0.669419  0.669419  1.000000  1.000000  1.000000   0.0   0.0  ...
6     0.669419  0.669419  1.000000  1.000000  1.000000   0.0   0.0  ...
7     0.669419  0.669419  1.000000  1.000000  1.000000   0.0   0.0  ...
8     0.000000  0.000000  0.000000  0.000000  0.000000   1.0   1.0  ...
9     0.000000  0.000000  0.000000  0.000000  0.000000   1.0   1.0  ...
10    0.000000  0.000000  0.000000  0.000000  0.000000   1.0   1.0  ...
11    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
12    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
13    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
14    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
15    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
16    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
17    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
18    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
19    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
20    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
21    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
22    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
23    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
24    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
25    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
26    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
27    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
28    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
29    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
...        ...       ...       ...       ...       ...   ...   ...  ...
1363  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1364  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1365  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1366  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1367  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1368  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1369  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1370  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1371  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1372  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1373  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1374  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1375  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1376  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1377  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1378  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1379  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1380  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1381  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1382  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1383  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1384  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1385  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1386  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1387  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1388  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1389  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1390  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1391  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1392  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...

      1383  1384  1385  1386  1387  1388  1389  1390  1391  1392
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
5      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
6      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
7      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
8      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
9      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
10     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
11     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
12     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
13     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
14     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
15     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
16     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
17     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
18     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
19     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
20     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
21     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
22     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
23     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
24     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
25     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
26     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
27     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
28     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
29     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
1363   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1364   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1365   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1366   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1367   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1368   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1369   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1370   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1371   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1372   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1373   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1374   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1375   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1376   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1377   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1378   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1379   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1380   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1381   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1382   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1383   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1384   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1385   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1386   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1387   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1388   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1389   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1390   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1391   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1392   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0

[1393 rows x 1393 columns]
Printing first 10 similarity values for Degrees_new_FieldOfStudy_Skills_new:
                                                   0         1         2     \
0     Rotating Equipments in Oil & Gas Industry Stat...  1.000000  0.000000
1     Reporting & Analysis SAP Financial Control Bud...  0.000000  1.000000
2     Reporting & Analysis SAP Financial Control Bud...  0.000000  1.000000
3     Reporting & Analysis SAP Financial Control Bud...  0.000000  1.000000
4     Reporting & Analysis SAP Financial Control Bud...  0.000000  1.000000
5     Reporting & Analysis SAP Financial Control Bud...  0.000000  1.000000
6     Reporting & Analysis SAP Financial Control Bud...  0.000000  1.000000
7     Reporting & Analysis SAP Financial Control Bud...  0.000000  1.000000
8     Reporting & Analysis SAP Financial Control Bud...  0.000000  1.000000
9     Reporting & Analysis SAP Financial Control Bud...  0.000000  1.000000
10    Event Planning Teamwork Customer Relations Neg...  0.000000  0.059961
11    Event Planning Teamwork Customer Relations Neg...  0.000000  0.059961
12    Event Planning Teamwork Customer Relations Neg...  0.000000  0.059961
13    Event Planning Teamwork Customer Relations Neg...  0.000000  0.059961
14    Event Planning Teamwork Customer Relations Neg...  0.000000  0.059961
15    Event Planning Teamwork Customer Relations Neg...  0.000000  0.059961
16    Event Planning Teamwork Customer Relations Neg...  0.000000  0.059961
17    Event Planning Teamwork Customer Relations Neg...  0.000000  0.059961
18    Event Planning Teamwork Customer Relations Neg...  0.000000  0.059961
19    Wireless Sensor Networks Wireless QoS    nan  ...  0.000000  0.000000
20    Wireless Sensor Networks Wireless QoS    nan  ...  0.000000  0.000000
21    Wireless Sensor Networks Wireless QoS    nan  ...  0.000000  0.000000
22    Wireless Sensor Networks Wireless QoS    nan  ...  0.000000  0.000000
23    Pharmacokinetics DMPK Clinical Development Pha...  0.000000  0.000000
24    Pharmacokinetics DMPK Clinical Development Pha...  0.000000  0.000000
25    Proactivo Responsable   Sistemas Sistemas  Mae...  0.000000  0.071264

In [298]:
matrix_skill_df_new = pd.DataFrame(matrix_skill)
matrix_skill_df_new.to_csv('matrix_skill_df_new.csv')

In [299]:
matrix_skill_read_new = pd.read_csv('matrix_skill_df_new.csv')

In [300]:
matrix_skill_df = pd.DataFrame(matrix_skill_read_new)

In [220]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
d = np.zeros((N2+2,N2+2))
matrix_pos_com = pd.DataFrame(d)
count_i = 0 

for i in S2:
    count_j = 0 
    matrix_pos_com.iloc[count_i,count_j] = i
    #print("This is the first one"+ matrix.iloc[count_i,count_j])
    
    #print(i)
   
    bow_i = i.split(" ")
    
    for j in S2:
        count_j +=1
        
        #print(j)

        train_set = [i,j]

        tfidf_vectorizer = TfidfVectorizer()
        tfidf_matrix_train = tfidf_vectorizer.fit_transform(train_set)  #finds the tfidf score with normalization
        cosine_scores = cosine_similarity(tfidf_matrix_train[0:1], tfidf_matrix_train)
        matrix_pos_com.iloc[count_i,count_j] = cosine_scores[:,1]
    print("values of i completed:")
    print(count_i)
    count_i += 1
print("Printing first 10 similarity values for positions__title:")  
print(matrix_pos_com)

Printing first 10 similarity values for positions__title:
                                                0     1         2     \
0                   Mechanical Maintenance Engineer    0.0  0.000000
1     Contrôleur de gestion opérationnel Département   1.0  0.000000
2     Contrôleur de gestion opérationnel Département   0.0  1.000000
3     Contrôleur de gestion opérationnel Département   0.0  1.000000
4          Contrôleur de gestion opérationnel Projet   0.0  1.000000
5          Contrôleur de gestion opérationnel Projet   0.0  0.669419
6          Contrôleur de gestion opérationnel Projet   0.0  0.669419
7              Stagiaire en Finances et comptabilité   0.0  0.669419
8              Stagiaire en Finances et comptabilité   0.0  0.000000
9              Stagiaire en Finances et comptabilité   0.0  0.000000
10                                                 0   0.0  0.000000
11                                                 0   0.0  0.000000
12                                                 0   0.0  0.000000
13                                                 0   0.0  0.000000
14                                                 0   0.0  0.000000
15                                                 0   0.0  0.000000
16                                                 0   0.0  0.000000
17                                                 0   0.0  0.000000
18                                                 0   0.0  0.000000
19                                                 0   0.0  0.000000
20                                                 0   0.0  0.000000
21                                                 0   0.0  0.000000
22                                                 0   0.0  0.000000
23                                                 0   0.0  0.000000
24                                                 0   0.0  0.000000
25                                                 0   0.0  0.000000
26                                                 0   0.0  0.000000
27                                                 0   0.0  0.000000
28                                                 0   0.0  0.000000
29                                                 0   0.0  0.000000
...                                              ...   ...       ...
1363                                               0   0.0  0.000000
1364                                               0   0.0  0.000000
1365                                               0   0.0  0.000000
1366                                               0   0.0  0.000000
1367                                               0   0.0  0.000000
1368                                               0   0.0  0.000000
1369                                               0   0.0  0.000000
1370                                               0   0.0  0.000000
1371                                               0   0.0  0.000000
1372                                               0   0.0  0.000000
1373                                               0   0.0  0.000000
1374                                               0   0.0  0.000000
1375                                               0   0.0  0.000000
1376                                               0   0.0  0.000000
1377                                               0   0.0  0.000000
1378                                               0   0.0  0.000000
1379                                               0   0.0  0.000000
1380                                               0   0.0  0.000000
1381                                               0   0.0  0.000000
1382                                               0   0.0  0.000000
1383                                               0   0.0  0.000000
1384                                               0   0.0  0.000000
1385                                               0   0.0  0.000000
1386                                               0   0.0  0.000000
1387                                               0   0.0  0.000000
1388                                               0   0.0  0.000000
1389                                               0   0.0  0.000000
1390                                               0   0.0  0.000000
1391                                               0   0.0  0.000000
1392                                               0   0.0  0.000000

          3         4         5         6         7     8     9     ...   \
0     0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1     0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
2     1.000000  1.000000  0.669419  0.669419  0.669419   0.0   0.0  ...
3     1.000000  1.000000  0.669419  0.669419  0.669419   0.0   0.0  ...
4     1.000000  1.000000  0.669419  0.669419  0.669419   0.0   0.0  ...
5     0.669419  0.669419  1.000000  1.000000  1.000000   0.0   0.0  ...
6     0.669419  0.669419  1.000000  1.000000  1.000000   0.0   0.0  ...
7     0.669419  0.669419  1.000000  1.000000  1.000000   0.0   0.0  ...
8     0.000000  0.000000  0.000000  0.000000  0.000000   1.0   1.0  ...
9     0.000000  0.000000  0.000000  0.000000  0.000000   1.0   1.0  ...
10    0.000000  0.000000  0.000000  0.000000  0.000000   1.0   1.0  ...
11    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
12    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
13    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
14    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
15    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
16    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
17    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
18    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
19    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
20    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
21    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
22    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
23    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
24    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
25    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
26    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
27    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
28    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
29    0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
...        ...       ...       ...       ...       ...   ...   ...  ...
1363  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1364  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1365  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1366  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1367  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1368  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1369  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1370  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1371  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1372  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1373  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1374  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1375  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1376  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1377  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1378  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1379  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1380  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1381  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1382  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1383  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1384  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1385  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1386  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1387  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1388  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1389  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1390  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1391  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...
1392  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0  ...

      1383  1384  1385  1386  1387  1388  1389  1390  1391  1392
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
5      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
6      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
7      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
8      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
9      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
10     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
11     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
12     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
13     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
14     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
15     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
16     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
17     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
18     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
19     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
20     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
21     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
22     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
23     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
24     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
25     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
26     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
27     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
28     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
29     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
1363   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1364   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1365   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1366   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1367   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1368   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1369   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1370   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1371   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1372   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1373   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1374   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1375   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1376   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1377   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1378   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1379   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1380   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1381   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1382   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1383   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1384   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1385   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1386   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1387   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1388   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1389   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1390   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1391   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1392   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0

[1393 rows x 1393 columns]

In [285]:
ew_compare_matrix_1 = pd.DataFrame(matrix_pos_com_df[0])
ew_compare_matrix_1.head()

                                                0
0                Mechanical Maintenance Engineer
1  Contrôleur de gestion opérationnel Département
2  Contrôleur de gestion opérationnel Département
3  Contrôleur de gestion opérationnel Département
4       Contrôleur de gestion opérationnel Projet

In [288]:
new_compare_skill_mat =matrix_skill_df[0]

In [295]:

#ew_compare_matrix_1.insert(1,'skills',new_compare_skill_mat)
#ew_compare_matrix_1.head(-100)

,0,skills
0,Mechanical Maintenance Engineer,Rotating Equipments in Oil & Gas Industry Stat...
1,Contrôleur de gestion opérationnel Département,Reporting & Analysis SAP Financial Control Bud...
2,Contrôleur de gestion opérationnel Département,Reporting & Analysis SAP Financial Control Bud...
3,Contrôleur de gestion opérationnel Département,Reporting & Analysis SAP Financial Control Bud...
4,Contrôleur de gestion opérationnel Projet,Reporting & Analysis SAP Financial Control Bud...
5,Contrôleur de gestion opérationnel Projet,Reporting & Analysis SAP Financial Control Bud...
6,Contrôleur de gestion opérationnel Projet,Reporting & Analysis SAP Financial Control Bud...
7,Stagiaire en Finances et comptabilité,Reporting & Analysis SAP Financial Control Bud...
8,Stagiaire en Finances et comptabilité,Reporting & Analysis SAP Financial Control Bud...
9,Stagiaire en Finances et comptabilité,Reporting & Analysis SAP Financial Control Bud...
10,0,Event Planning Teamwork Customer Relations Neg...
11,0,0
12,0,0
13,0,0
14,0,0
15,0,0
16,0,0
17,0,0
18,0,0
19,0,0
20,0,0
21,0,0
22,0,0
23,0,0
24,0,0
25,0,0
26,0,0
27,0,0
28,0,0
29,0,0
...,...,...
1263,0,0
1264,0,0
1265,0,0
1266,0,0
1267,0,0
1268,0,0
1269,0,0
1270,0,0
1271,0,0
1272,0,0
1273,0,0
1274,0,0
1275,0,0
1276,0,0
1277,0,0
1278,0,0
1279,0,0
1280,0,0
1281,0,0
1282,0,0
1283,0,0
1284,0,0
1285,0,0
1286,0,0
1287,0,0
1288,0,0
1289,0,0
1290,0,0
1291,0,0
1292,0,0

In [242]:
matrix_pos_com_df = pd.DataFrame(matrix_pos_com)

In [254]:
matrix_pos_com_1 = matrix_pos_com_df[0].values.tolist()
df_string_match_index = matrix_pos_com_1.index('Contrôleur de gestion opérationnel Projet')
print(df_string_match_index)

4

In [294]:
matrix_matched_element = matrix_pos_com_df.iloc[df_string_match_index,1:]
sagar_1 = matrix_matched_element.sort_values(ascending=False)
hero = sagar_1.index
find_postions = hero[0:10]
check_positions_comparison = ew_compare_matrix_1.iloc[find_postions,1]
print(check_positions_comparison)

2       Reporting & Analysis SAP Financial Control Bud...
3       Reporting & Analysis SAP Financial Control Bud...
4       Reporting & Analysis SAP Financial Control Bud...
5       Reporting & Analysis SAP Financial Control Bud...
6       Reporting & Analysis SAP Financial Control Bud...
7       Reporting & Analysis SAP Financial Control Bud...
1161                                                    0
1162                                                    0
1163                                                    0
37                                                      0
Name: skills, dtype: object